name: Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test WDF Compiler
    runs-on: [self-hosted, macOS]

    steps:
    - name: Setup environment
      run: source ~/.bashrc

    - name: Jai check
      run: jai -version

    - name: Build wdf_compiler
      working-directory: compiler
      run: jai wdf_compiler.jai

    - name: RC Lowpass Test
      working-directory: tests/rc_lowpass
      run: |
        ../../compiler/wdf_compiler rc_lowpass.wdf
        clang rc_lowpass.cpp --std=c++20 -lstdc++ -o rc_lowpass.exe && ./rc_lowpass.exe
