name: Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build_and_test:
    name: Test WDF Compiler
    runs-on: [self-hosted, macOS]

    steps:
    - name: Jai check
      run: ~/ChowDSP/jai/bin/jai-macos -version

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build wdf_compiler
      working-directory: compiler
      run: ~/ChowDSP/jai/bin/jai-macos wdf_compiler.jai

    - name: Run Tests
      run: bash tests/test_runner.sh gcc bad_configs

    - name: Run Bench
      run: bash tests/test_runner.sh gcc bench
